In [115]:
#Vectorized version of exercise 1
#Confirm that this is correct by comparing it to the original,
#double forloop version
import numpy as np


In [119]:
R = 0.01097 #In nanometers
m = np.array((1,2,3)) #First three series
n = np.array((1,2,3,4,5)*3) #The first five lines

print("Shape of m:",m.shape)
print("Contents of m:")
print(m)
print("Shape of n:",n.shape)
print("Contents of n:")
print(n)
    


Shape of m: (3,)
Contents of m:
[1 2 3]
Shape of n: (15,)
Contents of n:
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [120]:

#Create column vectors of [3,1] and [3,5]
m = m.reshape((m.shape[0],1))
n = n.reshape((3,5))

print("Shape of n:",n.shape)
print("Shape of m:",m.shape)



Shape of n: (3, 5)
Shape of m: (3, 1)


In [121]:
#Add i to n so that n >m in all cases
n += m

k = (1/(m**2)-1/(n**2))
invlambda = R*k

print("n:")
print(n)
print("\nm:")
print(m)
print("\n1/m**2")
print(1/(m**2))
print("\n1/n**2:")
print(1/(n**2))
print("\nlambda=", 1/invlambda,"nm")

n:
[[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]

m:
[[1]
 [2]
 [3]]

1/m**2
[[1.        ]
 [0.25      ]
 [0.11111111]]

1/n**2:
[[0.25       0.11111111 0.0625     0.04       0.02777778]
 [0.11111111 0.0625     0.04       0.02777778 0.02040816]
 [0.0625     0.04       0.02777778 0.02040816 0.015625  ]]

lambda= [[ 121.54360377  102.55241568   97.23488301   94.95594044   93.76220862]
 [ 656.33546035  486.17441507  434.08429917  410.20966272  397.04243897]
 [1875.24417242 1281.90519599 1093.89243391 1005.01367366  954.6697605 ]] nm


In [122]:
R = 1.097e-2
for m in [1,2,3]:
    print("Series for m = ", m)
    for k in [1,2,3,4,5]:
        n = m + k
        #invlambda = R*(1.0/m**2 - 1/n**2)
        invlambda = R*(1.0/m**2 - 1/n**2)
        #print(1lambda) # variable names should not start with number

        #print("n=",n, "  ", 1/invlambda, "nm")
        #print(n, 1/invlambda, "nm")
        
        print       (m, n, 1/m**2, 1/n**2) #only works for python 2

Series for m =  1
1 2 1.0 0.25
1 3 1.0 0.1111111111111111
1 4 1.0 0.0625
1 5 1.0 0.04
1 6 1.0 0.027777777777777776
Series for m =  2
2 3 0.25 0.1111111111111111
2 4 0.25 0.0625
2 5 0.25 0.04
2 6 0.25 0.027777777777777776
2 7 0.25 0.02040816326530612
Series for m =  3
3 4 0.1111111111111111 0.0625
3 5 0.1111111111111111 0.04
3 6 0.1111111111111111 0.027777777777777776
3 7 0.1111111111111111 0.02040816326530612
3 8 0.1111111111111111 0.015625
